CREATE DATABASE IF NOT EXISTS php_app;

CREATE USER IF NOT EXISTS testuser
    IDENTIFIED BY '9999';

GRANT ALL ON php_app.* TO testuser;

CREATE TABLE IF NOT EXISTS books (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    sub_title VARCHAR(255),
    vol_number VARCHAR(50),
    image_url VARCHAR(255) NOT NULL,
    memo TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);